### ISSUE TITLE
Change Readme

### ISSUE THREAD

**Issue by mukdagr8** [dvlpp/privat#2]
Thanks for the package. Couple issues that threw me though 

Change `composer require dvlpp/privat` to `composer require dvlpp/privat:dev-master`

And then when adding the reference to the kernel file

> Add the following line at the end of the $middleware array of the app/Http/Kernel file:

it shouldn't be `$middleware` but rather the `$middlewaregroup` in the `web` array so the sessions will work

**Comment by dvlpp** [comment]
Yeah, thanks for this and apologies for the very long time without notice 😬. I've just updated the readme to link to the new version of the repo, which is [code16/privat](https://github.com/code16/privat). It's a backward compatible v2, with some new features (public waiting page) and a readme up to date.
