### ISSUE TITLE
Reverse functionality of except.

### ISSUE THREAD

**Issue by hirani89** [dvlpp/privat#4]
Hi,

I want to restrict only certain pages not the whole site. And my site has dynamic urls so I can not list them all in the `except` param. Can I use wildcard to achieve this?

Regards,

**Comment by dvlpp** [comment]
Hi ; first notice that I moved privat from `dvlpp/privat` to `code16/privat`, with a v2 that allows public waiting page. I'll add a mention to that in the readme.

At the moment, Privat won't allow wildcards in the except URLs array. I'll look to it someday, but feel free to make a PR for that (in the `code16/privat` repo!).

**Comment by dvlpp** [comment]
Close and reopened here: https://github.com/code16/privat/issues/1.
